### ISSUE TITLE
Bug: poller status message replaces apply failure message in table printer

### ISSUE THREAD

**Issue by karlkfi** [kubernetes-sigs/cli-utils#518]
When applying an invalid Service (missing ports) I realized that the `kpt live apply --output table` output was showing me `Resource not found` instead of the apply error `The Service "cassandra" is invalid: spec.ports: Required value` which you get from kubectl apply.

I assume this means the status event for NotFound  was received after the apply event error and the table replaced the error with the status message. This seems like confusing behavior. The user probably wants to see the apply error and not any sort of status update from waiting (which was hopefully skipped for that object).

```
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: cassandra
spec:
  selector:
    app: cassandra
#  ports:
#  - port: 80
```
