### ISSUE TITLE
kstatus does not accept booleans for conditions

### ISSUE THREAD

**Issue by tim-jagenberg-piscada** [kubernetes-sigs/cli-utils#596]
Some resources use YAML booleans in their status conditions which are not interpreted by kstatus.

Kstatus should interpret both string and boolean representations for conditions.

For example the [new Keycloak Operator](https://github.com/keycloak/keycloak/tree/main/operator) uses booleans:

```YAML
status:
  conditions:
    - message: ''
      status: true
      type: Ready
    - message: ''
      status: false
      type: HasErrors
    - message: ''
      status: false
      type: RollingUpdate
```

This leads to the resource never being considered reconciled by Flux.
